#!/bin/bash
# Setup script for cursor-otel-hook (macOS/Linux)

set -e

echo "==================================="
echo "Cursor OTEL Hook Setup (Unix/macOS)"
echo "==================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Detect OS
OS_TYPE="$(uname -s)"
case "${OS_TYPE}" in
    Darwin*)    OS="macOS";;
    Linux*)     OS="Linux";;
    *)          OS="Unknown";;
esac

echo "Detected OS: ${OS}"
echo ""

# Check for Python
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: Python 3 is not installed${NC}"
    echo "Please install Python 3.8 or higher"
    exit 1
fi

PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
echo -e "${GREEN}✓${NC} Python ${PYTHON_VERSION} found"

# Create virtual environment if it doesn't exist
if [ ! -d "venv" ]; then
    echo ""
    echo "Creating virtual environment..."
    python3 -m venv venv
    echo -e "${GREEN}✓${NC} Virtual environment created"
else
    echo -e "${GREEN}✓${NC} Virtual environment already exists"
fi

# Activate virtual environment
source venv/bin/activate

# Upgrade pip
echo ""
echo "Upgrading pip..."
pip install --upgrade pip > /dev/null 2>&1
echo -e "${GREEN}✓${NC} pip upgraded"

# Install package
echo ""
echo "Installing cursor-otel-hook..."
pip install -e . > /dev/null 2>&1
echo -e "${GREEN}✓${NC} Package installed"

# Create hooks directory
CURSOR_HOOKS_DIR="$HOME/.cursor/hooks"
if [ ! -d "$CURSOR_HOOKS_DIR" ]; then
    echo ""
    echo "Creating Cursor hooks directory..."
    mkdir -p "$CURSOR_HOOKS_DIR"
    echo -e "${GREEN}✓${NC} Created $CURSOR_HOOKS_DIR"
fi

# Create config file in Cursor profile directory
CONFIG_FILE="$CURSOR_HOOKS_DIR/otel_config.json"
if [ ! -f "$CONFIG_FILE" ]; then
    echo ""
    echo "Creating OTEL configuration file..."
    cat > "$CONFIG_FILE" << 'EOF'
{
  "OTEL_EXPORTER_OTLP_ENDPOINT": "http://localhost:4317",
  "OTEL_SERVICE_NAME": "cursor-agent",
  "OTEL_EXPORTER_OTLP_PROTOCOL": "grpc",
  "OTEL_EXPORTER_OTLP_INSECURE": "true",
  "OTEL_EXPORTER_OTLP_HEADERS": null,
  "CURSOR_OTEL_MASK_PROMPTS": "false",
  "OTEL_EXPORTER_OTLP_TIMEOUT": "30"
}
EOF
    echo -e "${GREEN}✓${NC} Created $CONFIG_FILE"
else
    echo -e "${YELLOW}!${NC} Config already exists at $CONFIG_FILE"
fi

# Create wrapper script
WRAPPER_SCRIPT="$CURSOR_HOOKS_DIR/otel_hook.sh"
VENV_PATH="$(pwd)/venv"

echo ""
echo "Creating hook wrapper script..."
cat > "$WRAPPER_SCRIPT" << EOF
#!/bin/bash
# Cursor OTEL Hook Wrapper
# Auto-generated by setup.sh

# Activate virtual environment
source "$VENV_PATH/bin/activate"

# Run the hook with config file
exec python -m cursor_otel_hook --config "$CONFIG_FILE" "\$@"
EOF

chmod +x "$WRAPPER_SCRIPT"
echo -e "${GREEN}✓${NC} Created $WRAPPER_SCRIPT"

# Create/merge hooks.json configuration
HOOKS_CONFIG="$HOME/.cursor/hooks.json"
HOOK_EVENTS="sessionStart sessionEnd postToolUse afterShellExecution afterMCPExecution beforeReadFile afterFileEdit beforeSubmitPrompt subagentStart subagentStop stop"

merge_otel_hooks() {
    python3 - "$@" << 'PYEOF'
import json, sys

hooks_file = sys.argv[1]
hook_command = sys.argv[2]
events = sys.argv[3:]

with open(hooks_file, 'r') as f:
    data = json.load(f)

data.setdefault('version', 1)
data.setdefault('hooks', {})

changed = False
for event in events:
    entry = {'command': hook_command, 'timeout': 5}
    if event not in data['hooks']:
        data['hooks'][event] = [entry]
        changed = True
    else:
        cmds = [h.get('command', '') for h in data['hooks'][event]]
        if hook_command not in cmds:
            data['hooks'][event].append(entry)
            changed = True

if changed:
    with open(hooks_file, 'w') as f:
        json.dump(data, f, indent=2)
        f.write('\n')
PYEOF
}

echo ""
if [ -f "$HOOKS_CONFIG" ]; then
    echo "Merging otel hook into existing hooks.json..."
    if merge_otel_hooks "$HOOKS_CONFIG" "$WRAPPER_SCRIPT" $HOOK_EVENTS; then
        echo -e "${GREEN}✓${NC} Merged otel hooks into $HOOKS_CONFIG"
    else
        echo -e "${RED}✗${NC} Failed to merge hooks - you may need to manually add the otel hook entries"
    fi
else
    echo "Creating hooks.json configuration..."
    cat > "$HOOKS_CONFIG" << EOF
{
  "version": 1,
  "hooks": {
    "sessionStart": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ],
    "sessionEnd": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ],
    "postToolUse": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ],
    "afterShellExecution": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ],
    "afterMCPExecution": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ],
    "beforeReadFile": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ],
    "afterFileEdit": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ],
    "beforeSubmitPrompt": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ],
    "subagentStart": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ],
    "subagentStop": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ],
    "stop": [
      {
        "command": "$WRAPPER_SCRIPT",
        "timeout": 5
      }
    ]
  }
}
EOF
    echo -e "${GREEN}✓${NC} Created $HOOKS_CONFIG"
fi

# Copy example HTTP config for reference
EXAMPLE_HTTP_CONFIG="$PROJECT_DIR/otel_config_http.example.json"
if [ -f "$PROJECT_DIR/examples/otel_config_http.json" ]; then
    cp "$PROJECT_DIR/examples/otel_config_http.json" "$EXAMPLE_HTTP_CONFIG"
    echo ""
    echo -e "${GREEN}✓${NC} Copied HTTP config example to $EXAMPLE_HTTP_CONFIG"
fi

echo ""
echo -e "${GREEN}==================================="
echo "Setup Complete!"
echo "===================================${NC}"
echo ""
echo "Next steps:"
echo "1. Edit the configuration file to set your OTEL endpoint:"
echo "   $CONFIG_FILE"
echo ""
echo "   The config uses standard OTEL environment variable names:"
echo "   {"
echo "     \"OTEL_EXPORTER_OTLP_ENDPOINT\": \"http://your-collector:4317\","
echo "     \"OTEL_EXPORTER_OTLP_PROTOCOL\": \"grpc\","
echo "     \"OTEL_EXPORTER_OTLP_HEADERS\": {\"authorization\": \"Bearer YOUR_TOKEN\"}"
echo "   }"
echo ""
echo "2. Restart Cursor IDE to activate hooks"
echo ""
echo "Configuration files:"
echo "  - Hooks: $HOOKS_CONFIG"
echo "  - OTEL Config: $CONFIG_FILE"
echo "  - HTTP Example: $EXAMPLE_HTTP_CONFIG"
echo "  - Wrapper Script: $WRAPPER_SCRIPT"
echo ""
echo "To test manually:"
echo "  echo '{\"hook_event_name\":\"test\"}' | $WRAPPER_SCRIPT"
echo ""
echo "To edit config:"
echo "  nano $CONFIG_FILE"
echo "  # or: code $CONFIG_FILE, vim $CONFIG_FILE, etc."
echo ""
